version: '3.8'
name: redisinsight
services:

######## STORE ##########
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    environment:
      RIPROXYPATH: "/redisinsight"
    networks:
      - redisinsight-network
    expose:
      - "8001"
#########################

##### DOCKER NETWORK ####
networks:
  redisinsight-network:
    driver: bridge
  portainer_proxy-network:
    external: true
#########################x
