version: '3.8'
name: authentication
services:

  auth:
    image: necrelox/andesite-authentication:latest
    container_name: auth
    restart: unless-stopped
    depends_on:
      auth-database:
        condition: service_healthy
      auth-dragonfly:
        condition: service_started
    environment:
      HTTP_PORT: "${HTTP_PORT}"
      WS_PORT: "${WS_PORT}"
      ORIGINS: "${ORIGINS}"
      BASE_URL: "${BASE_URL}"
      DB_SERVER_HOST: "${DB_SERVER_HOST}"
      DB_SERVER_USER: "${DB_SERVER_USER}"
      DB_SERVER_PASSWORD: "${DB_SERVER_PASSWORD}"
      DB_SERVER_PORT: "${DB_SERVER_PORT}"
      DRAGONFLY_HOST: "${DRAGONFLY_HOST}"
      DRAGONFLY_PORT: "${DRAGONFLY_PORT}"
      RED_PANDA_BROKERS: "${RED_PANDA_BROKERS}"
      NODE_ENV: "production"
    networks:
      - auth-database-network
      - auth-dragonfly-network
      - red-panda_broker-network
      - portainer_proxy-network
    expose:
      - "${HTTP_PORT}"
      - "${WS_PORT}"

######## STORE ##########
  auth-dragonfly:
    container_name: dragonfly
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: unless-stopped
    ulimits:
      memlock: -1
    volumes:
      - dragonfly-data:/data
    networks:
      - auth-dragonfly-network
    expose:
      - "6379"
#########################

####### Database ########
  auth-database:
    container_name: auth-database
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${DB_SERVER_USER} -d authentication -p ${DB_SERVER_PORT}
      interval: 5s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: "authentication"
      POSTGRES_USER: "${DB_SERVER_USER}"
      POSTGRES_PASSWORD: "${DB_SERVER_PASSWORD}"
    command: -p ${DB_SERVER_PORT}
    volumes:
      - auth-database-data:/var/lib/postgresql/data
    networks:
      - auth-database-network
    expose:
      - "${DB_SERVER_PORT}"
#########################

##### DOCKER NETWORK ####
networks:
  auth-dragonfly-network:
    driver: bridge
  auth-database-network:
    driver: bridge
  red-panda_broker-network:
    external: true
  portainer_proxy-network:
    external: true
#########################x

##### DOCKER VOLUME #####
volumes:
  dragonfly-data:
  auth-database-data:
#########################
