version: '3.8'
name: authentication
services:

######## STORE ##########
  auth-dragonfly:
    container_name: dragonfly
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    restart: unless-stopped
    ulimits:
      memlock: -1
    volumes:
      - dragonfly-data:/data
    networks:
      - auth-dragonfly-network
      - redisinsight-network
    expose:
      - "6379"
    ports:
      - "6379:6379"

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:1.14.0
    restart: unless-stopped
    environment:
      RIPROXYPATH: "/redisinsight"
    networks:
      - redisinsight-network
    ports:
      - "8001:8001"
#########################

####### Database ########
  auth-database:
    container_name: auth-database
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${DB_SERVER_USER} -d authentication -p ${DB_SERVER_PORT}
      interval: 5s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: "authentication"
      POSTGRES_USER: "${DB_SERVER_USER}"
      POSTGRES_PASSWORD: "${DB_SERVER_PASSWORD}"
    command: -p ${DB_SERVER_PORT}
    volumes:
      - auth-database-data:/var/lib/postgresql/data
    networks:
      - auth-database-network
    expose:
      - "${DB_SERVER_PORT}"
    ports:
      - "${DB_SERVER_PORT}:${DB_SERVER_PORT}"

#########################

##### DOCKER NETWORK ####
networks:
  auth-dragonfly-network:
    driver: bridge
  auth-database-network:
    driver: bridge
  redisinsight-network:
    driver: bridge
  red-panda_broker-network:
    external: true
#########################x

##### DOCKER VOLUME #####
volumes:
  dragonfly-data:
  auth-database-data:
#########################
